In [1]:
import numpy as np

# Example 1: Reshaping to a matrix
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 matrix
reshaped_matrix = arr.reshape(2, 3)
print("Reshaped Matrix:")
print(reshaped_matrix)


Reshaped Matrix:
[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

# Example 2: Flattening a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the matrix to a 1D array
flattened_array = matrix.flatten()
print("Flattened Array:", flattened_array)


Flattened Array: [1 2 3 4 5 6]


In [3]:
import numpy as np

# Example 3: Reshaping with -1 for automatic calculation
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 matrix (automatically calculates the size)
reshaped_matrix_auto = arr.reshape(2, -1)
print("Reshaped Matrix (Automatic Calculation):")
print(reshaped_matrix_auto)


Reshaped Matrix (Automatic Calculation):
[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

# Example 4: Reshaping to a 3D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape to a 3x3x1 3D array
reshaped_3d_array = arr.reshape(3, 3, 1)
print("Reshaped 3D Array:")
print(reshaped_3d_array)


Reshaped 3D Array:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [5]:
import numpy as np

# Example 5: Transposing a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose the matrix
transposed_matrix = np.transpose(matrix)
print("Transposed Matrix:")
print(transposed_matrix)


Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]
