In [1]:
import numpy as np

# Example 1: Matrix addition
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result_addition = matrix1 + matrix2
print("Matrix Addition:")
print(result_addition)


Matrix Addition:
[[ 6  8]
 [10 12]]


In [2]:
import numpy as np

# Example 2: Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result_multiplication = np.dot(matrix1, matrix2)
print("Matrix Multiplication:")
print(result_multiplication)


Matrix Multiplication:
[[19 22]
 [43 50]]


In [3]:
import numpy as np

# Example 3: Transposing a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])

transposed_matrix = np.transpose(matrix)
print("Transposed Matrix:")
print(transposed_matrix)


Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np

# Example 4: Matrix inversion
matrix = np.array([[1, 2], [3, 4]])

inverse_matrix = np.linalg.inv(matrix)
print("Inverse Matrix:")
print(inverse_matrix)


Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
import numpy as np

# Example 5: Element-wise matrix operations
matrix = np.array([[1, 2], [3, 4]])

# Element-wise square root
result_sqrt = np.sqrt(matrix)
print("Element-wise Square Root:")
print(result_sqrt)

# Element-wise exponential
result_exp = np.exp(matrix)
print("Element-wise Exponential:")
print(result_exp)


Element-wise Square Root:
[[1.         1.41421356]
 [1.73205081 2.        ]]
Element-wise Exponential:
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
